# Generated by Django 5.0.3 on 2024-07-10 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('quantity', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('quantity',),
            },
        ),
        migrations.CreateModel(
            name='IngridentPerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('ingrident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ingrident')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('ingridents', models.ManyToManyField(related_name='ingridents_per_item', to='base.ingridentperitem')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantites', models.PositiveIntegerField()),
                ('bill', models.FloatField()),
                ('ordered_start_time', models.DateTimeField(auto_now_add=True)),
                ('ordered_end_time', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.item')),
            ],
        ),
    ]
