# Generated by Django 5.0.3 on 2024-07-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingrident',
            new_name='Ingridient',
        ),
        migrations.RenameModel(
            old_name='IngridentPerItem',
            new_name='IngridientPerItem',
        ),
        migrations.RenameField(
            model_name='ingridientperitem',
            old_name='ingrident',
            new_name='ingridient',
        ),
        migrations.RemoveField(
            model_name='item',
            name='ingridents',
        ),
        migrations.AddField(
            model_name='item',
            name='ingridients',
            field=models.ManyToManyField(related_name='ingridients_per_item', to='base.ingridientperitem'),
        ),
        migrations.AddField(
            model_name='item',
            name='veg',
            field=models.BooleanField(default=None),
        ),
    ]
