# Generated by Django 5.0.3 on 2024-07-10 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_ingrident_ingridient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ingridients',
        ),
        migrations.AddField(
            model_name='ingridientperitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.item'),
        ),
        migrations.AlterField(
            model_name='ingridientperitem',
            name='ingridient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ingridient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.item'),
        ),
    ]
