# Generated by Django 5.0.3 on 2024-07-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_item_status_inventory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='InventoryOrder',
        ),
    ]
