# Generated by Django 5.0.3 on 2024-07-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_inventory_inventoryorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryorder',
            name='interval',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
