# Generated by Django 5.0.3 on 2024-07-12 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_inventoryorder_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryorder',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ingridient'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(default='item', max_length=10),
        ),
        migrations.AlterField(
            model_name='ingridient',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ingridient',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
