# Generated by Django 5.0.3 on 2024-07-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_inventoryorder_code_order_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryorder',
            name='code',
        ),
    ]
